name: CI Python (FastAPI)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint avec Ruff
      run: |
        ruff check .

    - name: Tests avec Pytest + Couverture
      run: |
        python -m pytest --cov=src --cov-report=term-missing --cov-fail-under=80